os: osx
osx_image: xcode7.3

cache:
  directories:
    - /Library/Developer/Toolchains

before_install:
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
  
script:
  - swift build 
  - swift test
